#!/usr/bin/env python3
"""Build assets/manifest.js, the day list the course website reads.

Run from the repo root after adding, renaming or retitling a lesson:

    python3 scripts/build_site_manifest.py

It reads every WEEK_*/DAILY_TASKS/DAY_*.md (title from the "# DAY N:" line,
time and difficulty from the "**Week:** ... **Time:** ..." line) and pairs
each with its SOLUTIONS file. The output is committed, so hosting the site
needs no build step.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "manifest.js"

# Weeks grouped the way the README's COURSE STRUCTURE section groups them.
PHASES = [
    {"phase": 1, "name": "Foundation", "weeks": [1, 2],
     "outcome": "Get n8n running, learn triggers and nodes, and ship your first real automation."},
    {"phase": 2, "name": "Workflow building", "weeks": [3, 4, 5],
     "outcome": "Expressions, error handling, data processing, and running workflows in production."},
    {"phase": 3, "name": "AI integration", "weeks": [6, 7, 8],
     "outcome": "Put AI agents and LLMs inside your workflows, including an introduction to RAG."},
    {"phase": 4, "name": "Real-world tools", "weeks": [9, 10],
     "outcome": "OAuth, forms, email and calendar triggers, custom APIs and orchestration."},
    {"phase": 5, "name": "Business building", "weeks": [11, 12],
     "outcome": "Package your skills, win your first client, then scale with templates and a team."},
    {"phase": 6, "name": "Advanced business", "weeks": [13, 14, 15],
     "outcome": "Partnerships, brand, optimisation, and graduating with a portfolio."},
]

KEEP_UPPER = {"AI", "API", "APIS", "RAG", "LLM", "AAAS"}
KEEP_LOWER = {"with", "and", "of", "the", "to", "in", "for", "a"}


def nice_case(text: str) -> str:
    """'BUILDING WORKFLOWS WITH CONFIDENCE' -> 'Building workflows with confidence'."""
    words = text.split()
    out = []
    for i, w in enumerate(words):
        if w.upper() in KEEP_UPPER:
            out.append("AaaS" if w.upper() == "AAAS" else w.upper())
        elif i == 0:
            out.append(w.capitalize())
        else:
            out.append(w.lower())
    return " ".join(out)


def week_title(readme: Path) -> str:
    first = readme.read_text(encoding="utf-8").splitlines()[0]
    m = re.match(r"#\s*\S*\s*WEEK\s+\d+:\s*(.+)", first)
    title = m.group(1) if m else first.lstrip("# ")
    title = re.sub(r"\s*-\s*PART\s+(\d+)$", r", part \1", title)
    return nice_case(title)


def main() -> None:
    weeks, days = [], []
    for week_dir in sorted(ROOT.glob("WEEK_*")):
        wnum = int(week_dir.name.split("_")[1])
        weeks.append({
            "week": wnum,
            "dir": week_dir.name,
            "title": week_title(week_dir / "README.md"),
        })
        solutions = {p.stem: p for p in (week_dir / "SOLUTIONS").glob("DAY_*")}
        for lesson in sorted((week_dir / "DAILY_TASKS").glob("DAY_*.md")):
            lines = lesson.read_text(encoding="utf-8").splitlines()
            title = re.match(r"#\s*DAY\s+(\d+):\s*(.+)", lines[0])
            meta = lines[1] if len(lines) > 1 else ""
            time = re.search(r"\*\*Time:\*\*\s*([^|]+)", meta)
            level = re.search(r"\*\*Difficulty:\*\*\s*([^|]+)", meta)
            sol = solutions.get(lesson.stem)
            days.append({
                "day": int(title.group(1)),
                "week": wnum,
                "title": title.group(2).strip(),
                "time": time.group(1).strip() if time else "",
                "difficulty": level.group(1).strip() if level else "",
                "lesson": lesson.relative_to(ROOT).as_posix(),
                "solution": sol.relative_to(ROOT).as_posix() if sol else None,
            })

    days.sort(key=lambda d: d["day"])
    expected = list(range(1, len(days) + 1))
    if [d["day"] for d in days] != expected:
        raise SystemExit("Day numbers are not a continuous 1..N sequence")

    data = {"phases": PHASES, "weeks": weeks, "days": days}
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_site_manifest.py. Do not edit by hand.\n"
        "window.AP_COURSE = " + json.dumps(data, indent=1, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(weeks)} weeks, {len(days)} days")


if __name__ == "__main__":
    main()
